server:
  port: 8089
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rjzfrj/my-spring-cloud-config/
          search-paths: respo
      label: master
      
          
          
           