package com.allscore.wireless.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="businessMapper")
public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int countByExample(BusinessExample example);
    
    int countUsersBussinessCzByExample(BusinessExample example);
    
    int countUsersBussinessXfByExample(BusinessExample example);
    
    int countUsersBussinessTkByExample(BusinessExample example);
    
    int countUsersBussinessJfByExample(BusinessExample example);
    
    int countShopBusinessTxByExample(BusinessExample example);
    
    int countShopBusinessSellerPoolByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int deleteByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    List<Business> selectByExample(BusinessExample example);
    
    List<UsersBussiness> selectUsersBussinessCzByExample(BusinessExample example);
    
    List<UsersBussiness> selectUsersBussinessXfByExample(BusinessExample example);
    
    List<UsersBussiness> selectUsersBussinessTkByExample(BusinessExample example);
    
    List<UsersBussiness> selectUsersBussinessJfByExample(BusinessExample example);
    
    List<ShopBusiness> selectShopBusinessTxByExample(BusinessExample example);
    
    List<ShopBusiness> selectShopBusinessSellerPoolByExample(BusinessExample example);
    
    ShopBusiness selectSellerPoolSum(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    Business selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByExample(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByPrimaryKey(Business record);
}