package com.allscore.wireless.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


public class BusinessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected String orderByClause;
    
    protected String member_card;
    
    protected String mobile;
    
    protected String merchant_name;
    
    protected String status;
    
    protected String business_result;
    
    protected String serial;
    
    protected BigDecimal order_amt;
    
    protected String strDate;
    
    protected String endDate;
    
    protected String business_type;
    
    protected String source_serial;
    
    protected String business_source;
    
    protected String merchant_code;
    
    protected String id;
    
    protected Date tDate;
    
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public BusinessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }
    
    public Date gettDate() {
		return tDate;
	}

	public void settDate(Date tDate) {
		this.tDate = tDate;
	}
	

	public String getMerchant_code() {
		return merchant_code;
	}

	public void setMerchant_code(String merchant_code) {
		this.merchant_code = merchant_code == null ? null : ("".equals(merchant_code.trim())?null:merchant_code.trim());
	}

	public String getBusiness_source() {
		return business_source;
	}



	public void setBusiness_source(String businessSource) {
		this.business_source = businessSource == null ? null : ("".equals(businessSource.trim())?null:businessSource.trim());
	}



	public String getSource_serial() {
		return source_serial;
	}



	public void setSource_serial(String sourceSerial) {
		this.source_serial = sourceSerial == null ? null : ("".equals(sourceSerial.trim())?null:sourceSerial.trim());
	}



	public String getBusiness_type() {
		return business_type;
	}

	public void setBusiness_type(String businessType) {
		this.business_type = businessType == null ? null : ("".equals(businessType.trim())?null:businessType.trim());
		
	}



	public BigDecimal getOrder_amt() {
		return order_amt;
	}

	public void setOrder_amt(BigDecimal orderAmt) {
		this.order_amt = orderAmt;
		
	}


	public String getStrDate() {
		return strDate;
	}


	public void setStrDate(String strDate) {
		this.strDate = strDate;
	}


	public String getEndDate() {
		return endDate;
	}


	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}


	public String getSerial() {
		return serial;
	}


	public void setSerial(String serial) {
		this.serial = serial == null ? null : ("".equals(serial.trim())?null:serial.trim());
		//this.serial = serial;
	}


	public String getBusiness_result() {
		return business_result;
	}

	public void setBusiness_result(String businessResult) {
		this.business_result = businessResult == null ? null : ("".equals(businessResult.trim())?null:businessResult.trim());
		//business_result = businessResult;
	}


	public String getMember_card() {
		return member_card;
	}


	public void setMember_card(String memberCard) {
		this.member_card = memberCard == null ? null : ("".equals(memberCard.trim())?null:memberCard.trim());
		//member_card = memberCard;
	}


	public String getMobile() {
		return mobile;
	}



	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : ("".equals(mobile.trim())?null:mobile.trim());
		//this.mobile = mobile;
	}



	public String getMerchant_name() {
		return merchant_name;
	}


	public void setMerchant_name(String merchantName) {
		this.merchant_name = merchantName == null ? null : ("".equals(merchantName.trim())?null:merchantName.trim());
		//merchant_name = merchantName;
	}



	public String getStatus() {
		return status;
	}



	public void setStatus(String status) {
		this.status = status == null ? null : ("".equals(status.trim())?null:status.trim());
		//this.status = status;
	}
	
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDEqualTo(String value) {
            addCriterion("USER_ID =", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThan(String value) {
            addCriterion("USER_ID >", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThan(String value) {
            addCriterion("USER_ID <", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLike(String value) {
            addCriterion("USER_ID like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotLike(String value) {
            addCriterion("USER_ID not like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIn(List<String> values) {
            addCriterion("USER_ID in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDIsNull() {
            addCriterion("UNIONID is null");
            return (Criteria) this;
        }

        public Criteria andUNIONIDIsNotNull() {
            addCriterion("UNIONID is not null");
            return (Criteria) this;
        }

        public Criteria andUNIONIDEqualTo(String value) {
            addCriterion("UNIONID =", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDNotEqualTo(String value) {
            addCriterion("UNIONID <>", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDGreaterThan(String value) {
            addCriterion("UNIONID >", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDGreaterThanOrEqualTo(String value) {
            addCriterion("UNIONID >=", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDLessThan(String value) {
            addCriterion("UNIONID <", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDLessThanOrEqualTo(String value) {
            addCriterion("UNIONID <=", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDLike(String value) {
            addCriterion("UNIONID like", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDNotLike(String value) {
            addCriterion("UNIONID not like", value, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDIn(List<String> values) {
            addCriterion("UNIONID in", values, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDNotIn(List<String> values) {
            addCriterion("UNIONID not in", values, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDBetween(String value1, String value2) {
            addCriterion("UNIONID between", value1, value2, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andUNIONIDNotBetween(String value1, String value2) {
            addCriterion("UNIONID not between", value1, value2, "UNIONID");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEIsNull() {
            addCriterion("COUPON_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEIsNotNull() {
            addCriterion("COUPON_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEEqualTo(String value) {
            addCriterion("COUPON_TYPE =", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPENotEqualTo(String value) {
            addCriterion("COUPON_TYPE <>", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEGreaterThan(String value) {
            addCriterion("COUPON_TYPE >", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("COUPON_TYPE >=", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPELessThan(String value) {
            addCriterion("COUPON_TYPE <", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPELessThanOrEqualTo(String value) {
            addCriterion("COUPON_TYPE <=", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPELike(String value) {
            addCriterion("COUPON_TYPE like", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPENotLike(String value) {
            addCriterion("COUPON_TYPE not like", value, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEIn(List<String> values) {
            addCriterion("COUPON_TYPE in", values, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPENotIn(List<String> values) {
            addCriterion("COUPON_TYPE not in", values, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPEBetween(String value1, String value2) {
            addCriterion("COUPON_TYPE between", value1, value2, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andCOUPON_TYPENotBetween(String value1, String value2) {
            addCriterion("COUPON_TYPE not between", value1, value2, "COUPON_TYPE");
            return (Criteria) this;
        }

        public Criteria andAMOUNTIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAMOUNTIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAMOUNTEqualTo(BigDecimal value) {
            addCriterion("AMOUNT =", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTNotEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <>", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTGreaterThan(BigDecimal value) {
            addCriterion("AMOUNT >", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT >=", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTLessThan(BigDecimal value) {
            addCriterion("AMOUNT <", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <=", value, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTIn(List<BigDecimal> values) {
            addCriterion("AMOUNT in", values, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTNotIn(List<BigDecimal> values) {
            addCriterion("AMOUNT not in", values, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT between", value1, value2, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andAMOUNTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT not between", value1, value2, "AMOUNT");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEEqualTo(Date value) {
            addCriterion("START_DATE =", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotEqualTo(Date value) {
            addCriterion("START_DATE <>", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEGreaterThan(Date value) {
            addCriterion("START_DATE >", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("START_DATE >=", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATELessThan(Date value) {
            addCriterion("START_DATE <", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATELessThanOrEqualTo(Date value) {
            addCriterion("START_DATE <=", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIn(List<Date> values) {
            addCriterion("START_DATE in", values, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotIn(List<Date> values) {
            addCriterion("START_DATE not in", values, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEBetween(Date value1, Date value2) {
            addCriterion("START_DATE between", value1, value2, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotBetween(Date value1, Date value2) {
            addCriterion("START_DATE not between", value1, value2, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATEIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEND_DATEIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEND_DATEEqualTo(Date value) {
            addCriterion("END_DATE =", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATENotEqualTo(Date value) {
            addCriterion("END_DATE <>", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATEGreaterThan(Date value) {
            addCriterion("END_DATE >", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("END_DATE >=", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATELessThan(Date value) {
            addCriterion("END_DATE <", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATELessThanOrEqualTo(Date value) {
            addCriterion("END_DATE <=", value, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATEIn(List<Date> values) {
            addCriterion("END_DATE in", values, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATENotIn(List<Date> values) {
            addCriterion("END_DATE not in", values, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATEBetween(Date value1, Date value2) {
            addCriterion("END_DATE between", value1, value2, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andEND_DATENotBetween(Date value1, Date value2) {
            addCriterion("END_DATE not between", value1, value2, "END_DATE");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }
        
        public Criteria andMEMBER_CARDLike(String value) {
            addCriterion("MEMBER_CARD like", value, "MEMBER_CARD");
            return (Criteria) this;
        }
        
        public Criteria andMERCHANT_NAMELike(String value) {
            addCriterion("MERCHANT_NAME like", value, "MERCHANT_NAME");
            return (Criteria) this;
        }
        
        public Criteria andMOBILELike(String value) {
            addCriterion("MOBILE like", value, "MOBILE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_COUPON
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 27 15:12:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_COUPON
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}