package com.allscore.wireless.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CheckErrorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected Integer limitEnd;
    
    protected String strDate;
    
    protected String endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public CheckErrorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }
    
    public String getStrDate() {
		return strDate;
	}
	public void setStrDate(String strDate) {
		this.strDate = strDate;
	}
	public String getEndDate() {
		return endDate;
	}
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDEqualTo(String value) {
            addCriterion("USER_ID =", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThan(String value) {
            addCriterion("USER_ID >", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThan(String value) {
            addCriterion("USER_ID <", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLike(String value) {
            addCriterion("USER_ID like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotLike(String value) {
            addCriterion("USER_ID not like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIn(List<String> values) {
            addCriterion("USER_ID in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIsNull() {
            addCriterion("CARD_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBEREqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLike(String value) {
            addCriterion("CARD_NUMBER like", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIn(List<String> values) {
            addCriterion("CARD_NUMBER in", values, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotIn(List<String> values) {
            addCriterion("CARD_NUMBER not in", values, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIsNull() {
            addCriterion("TRAN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIsNotNull() {
            addCriterion("TRAN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT =", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <>", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTGreaterThan(BigDecimal value) {
            addCriterion("TRAN_AMT >", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT >=", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTLessThan(BigDecimal value) {
            addCriterion("TRAN_AMT <", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <=", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT in", values, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT not in", values, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT between", value1, value2, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT not between", value1, value2, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIsNull() {
            addCriterion("POUNDAGE is null");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIsNotNull() {
            addCriterion("POUNDAGE is not null");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE =", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE <>", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEGreaterThan(BigDecimal value) {
            addCriterion("POUNDAGE >", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE >=", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGELessThan(BigDecimal value) {
            addCriterion("POUNDAGE <", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGELessThanOrEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE <=", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIn(List<BigDecimal> values) {
            addCriterion("POUNDAGE in", values, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotIn(List<BigDecimal> values) {
            addCriterion("POUNDAGE not in", values, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POUNDAGE between", value1, value2, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POUNDAGE not between", value1, value2, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andSERIALIsNull() {
            addCriterion("SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andSERIALIsNotNull() {
            addCriterion("SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andSERIALEqualTo(String value) {
            addCriterion("SERIAL =", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotEqualTo(String value) {
            addCriterion("SERIAL <>", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALGreaterThan(String value) {
            addCriterion("SERIAL >", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL >=", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLessThan(String value) {
            addCriterion("SERIAL <", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLessThanOrEqualTo(String value) {
            addCriterion("SERIAL <=", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLike(String value) {
            addCriterion("SERIAL like", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotLike(String value) {
            addCriterion("SERIAL not like", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALIn(List<String> values) {
            addCriterion("SERIAL in", values, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotIn(List<String> values) {
            addCriterion("SERIAL not in", values, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALBetween(String value1, String value2) {
            addCriterion("SERIAL between", value1, value2, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotBetween(String value1, String value2) {
            addCriterion("SERIAL not between", value1, value2, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTIsNull() {
            addCriterion("CHECK_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTIsNotNull() {
            addCriterion("CHECK_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTEqualTo(String value) {
            addCriterion("CHECK_RESULT =", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTNotEqualTo(String value) {
            addCriterion("CHECK_RESULT <>", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTGreaterThan(String value) {
            addCriterion("CHECK_RESULT >", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_RESULT >=", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTLessThan(String value) {
            addCriterion("CHECK_RESULT <", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTLessThanOrEqualTo(String value) {
            addCriterion("CHECK_RESULT <=", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTLike(String value) {
            addCriterion("CHECK_RESULT like", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTNotLike(String value) {
            addCriterion("CHECK_RESULT not like", value, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTIn(List<String> values) {
            addCriterion("CHECK_RESULT in", values, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTNotIn(List<String> values) {
            addCriterion("CHECK_RESULT not in", values, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTBetween(String value1, String value2) {
            addCriterion("CHECK_RESULT between", value1, value2, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andCHECK_RESULTNotBetween(String value1, String value2) {
            addCriterion("CHECK_RESULT not between", value1, value2, "CHECK_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTIsNull() {
            addCriterion("HANDLE_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTIsNotNull() {
            addCriterion("HANDLE_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTEqualTo(String value) {
            addCriterion("HANDLE_RESULT =", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTNotEqualTo(String value) {
            addCriterion("HANDLE_RESULT <>", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTGreaterThan(String value) {
            addCriterion("HANDLE_RESULT >", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLE_RESULT >=", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTLessThan(String value) {
            addCriterion("HANDLE_RESULT <", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTLessThanOrEqualTo(String value) {
            addCriterion("HANDLE_RESULT <=", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTLike(String value) {
            addCriterion("HANDLE_RESULT like", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTNotLike(String value) {
            addCriterion("HANDLE_RESULT not like", value, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTIn(List<String> values) {
            addCriterion("HANDLE_RESULT in", values, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTNotIn(List<String> values) {
            addCriterion("HANDLE_RESULT not in", values, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTBetween(String value1, String value2) {
            addCriterion("HANDLE_RESULT between", value1, value2, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_RESULTNotBetween(String value1, String value2) {
            addCriterion("HANDLE_RESULT not between", value1, value2, "HANDLE_RESULT");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEIsNull() {
            addCriterion("HANDLE_CAUSE is null");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEIsNotNull() {
            addCriterion("HANDLE_CAUSE is not null");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEEqualTo(String value) {
            addCriterion("HANDLE_CAUSE =", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSENotEqualTo(String value) {
            addCriterion("HANDLE_CAUSE <>", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEGreaterThan(String value) {
            addCriterion("HANDLE_CAUSE >", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLE_CAUSE >=", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSELessThan(String value) {
            addCriterion("HANDLE_CAUSE <", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSELessThanOrEqualTo(String value) {
            addCriterion("HANDLE_CAUSE <=", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSELike(String value) {
            addCriterion("HANDLE_CAUSE like", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSENotLike(String value) {
            addCriterion("HANDLE_CAUSE not like", value, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEIn(List<String> values) {
            addCriterion("HANDLE_CAUSE in", values, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSENotIn(List<String> values) {
            addCriterion("HANDLE_CAUSE not in", values, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSEBetween(String value1, String value2) {
            addCriterion("HANDLE_CAUSE between", value1, value2, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andHANDLE_CAUSENotBetween(String value1, String value2) {
            addCriterion("HANDLE_CAUSE not between", value1, value2, "HANDLE_CAUSE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEIsNull() {
            addCriterion("BUSINESS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEIsNotNull() {
            addCriterion("BUSINESS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEEqualTo(String value) {
            addCriterion("BUSINESS_DATE =", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATENotEqualTo(String value) {
            addCriterion("BUSINESS_DATE <>", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEGreaterThan(String value) {
            addCriterion("BUSINESS_DATE >", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_DATE >=", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATELessThan(String value) {
            addCriterion("BUSINESS_DATE <", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATELessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_DATE <=", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATELike(String value) {
            addCriterion("BUSINESS_DATE like", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATENotLike(String value) {
            addCriterion("BUSINESS_DATE not like", value, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEIn(List<String> values) {
            addCriterion("BUSINESS_DATE in", values, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATENotIn(List<String> values) {
            addCriterion("BUSINESS_DATE not in", values, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATEBetween(String value1, String value2) {
            addCriterion("BUSINESS_DATE between", value1, value2, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_DATENotBetween(String value1, String value2) {
            addCriterion("BUSINESS_DATE not between", value1, value2, "BUSINESS_DATE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIsNull() {
            addCriterion("BUSINESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIsNotNull() {
            addCriterion("BUSINESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEEqualTo(String value) {
            addCriterion("BUSINESS_TIME =", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotEqualTo(String value) {
            addCriterion("BUSINESS_TIME <>", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEGreaterThan(String value) {
            addCriterion("BUSINESS_TIME >", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TIME >=", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMELessThan(String value) {
            addCriterion("BUSINESS_TIME <", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMELessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TIME <=", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMELike(String value) {
            addCriterion("BUSINESS_TIME like", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotLike(String value) {
            addCriterion("BUSINESS_TIME not like", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIn(List<String> values) {
            addCriterion("BUSINESS_TIME in", values, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotIn(List<String> values) {
            addCriterion("BUSINESS_TIME not in", values, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEBetween(String value1, String value2) {
            addCriterion("BUSINESS_TIME between", value1, value2, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TIME not between", value1, value2, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIsNull() {
            addCriterion("ORDER_AMT is null");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIsNotNull() {
            addCriterion("ORDER_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT =", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT <>", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTGreaterThan(BigDecimal value) {
            addCriterion("ORDER_AMT >", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT >=", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTLessThan(BigDecimal value) {
            addCriterion("ORDER_AMT <", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT <=", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMT in", values, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMT not in", values, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMT between", value1, value2, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMT not between", value1, value2, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEIsNull() {
            addCriterion("SETTLEMENT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEIsNotNull() {
            addCriterion("SETTLEMENT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEEqualTo(Date value) {
            addCriterion("SETTLEMENT_DATE =", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATENotEqualTo(Date value) {
            addCriterion("SETTLEMENT_DATE <>", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEGreaterThan(Date value) {
            addCriterion("SETTLEMENT_DATE >", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("SETTLEMENT_DATE >=", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATELessThan(Date value) {
            addCriterion("SETTLEMENT_DATE <", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATELessThanOrEqualTo(Date value) {
            addCriterion("SETTLEMENT_DATE <=", value, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEIn(List<Date> values) {
            addCriterion("SETTLEMENT_DATE in", values, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATENotIn(List<Date> values) {
            addCriterion("SETTLEMENT_DATE not in", values, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATEBetween(Date value1, Date value2) {
            addCriterion("SETTLEMENT_DATE between", value1, value2, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andSETTLEMENT_DATENotBetween(Date value1, Date value2) {
            addCriterion("SETTLEMENT_DATE not between", value1, value2, "SETTLEMENT_DATE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIsNull() {
            addCriterion("MERCHANT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIsNotNull() {
            addCriterion("MERCHANT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEEqualTo(String value) {
            addCriterion("MERCHANT_NAME =", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotEqualTo(String value) {
            addCriterion("MERCHANT_NAME <>", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEGreaterThan(String value) {
            addCriterion("MERCHANT_NAME >", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME >=", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELessThan(String value) {
            addCriterion("MERCHANT_NAME <", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME <=", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELike(String value) {
            addCriterion("MERCHANT_NAME like", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotLike(String value) {
            addCriterion("MERCHANT_NAME not like", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIn(List<String> values) {
            addCriterion("MERCHANT_NAME in", values, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotIn(List<String> values) {
            addCriterion("MERCHANT_NAME not in", values, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME between", value1, value2, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME not between", value1, value2, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDIsNull() {
            addCriterion("CLIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDIsNotNull() {
            addCriterion("CLIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDEqualTo(String value) {
            addCriterion("CLIENT_ID =", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDNotEqualTo(String value) {
            addCriterion("CLIENT_ID <>", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDGreaterThan(String value) {
            addCriterion("CLIENT_ID >", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDGreaterThanOrEqualTo(String value) {
            addCriterion("CLIENT_ID >=", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDLessThan(String value) {
            addCriterion("CLIENT_ID <", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDLessThanOrEqualTo(String value) {
            addCriterion("CLIENT_ID <=", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDLike(String value) {
            addCriterion("CLIENT_ID like", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDNotLike(String value) {
            addCriterion("CLIENT_ID not like", value, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDIn(List<String> values) {
            addCriterion("CLIENT_ID in", values, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDNotIn(List<String> values) {
            addCriterion("CLIENT_ID not in", values, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDBetween(String value1, String value2) {
            addCriterion("CLIENT_ID between", value1, value2, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andCLIENT_IDNotBetween(String value1, String value2) {
            addCriterion("CLIENT_ID not between", value1, value2, "CLIENT_ID");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTIsNull() {
            addCriterion("REVIEW_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTIsNotNull() {
            addCriterion("REVIEW_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTEqualTo(String value) {
            addCriterion("REVIEW_RESULT =", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTNotEqualTo(String value) {
            addCriterion("REVIEW_RESULT <>", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTGreaterThan(String value) {
            addCriterion("REVIEW_RESULT >", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTGreaterThanOrEqualTo(String value) {
            addCriterion("REVIEW_RESULT >=", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTLessThan(String value) {
            addCriterion("REVIEW_RESULT <", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTLessThanOrEqualTo(String value) {
            addCriterion("REVIEW_RESULT <=", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTLike(String value) {
            addCriterion("REVIEW_RESULT like", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTNotLike(String value) {
            addCriterion("REVIEW_RESULT not like", value, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTIn(List<String> values) {
            addCriterion("REVIEW_RESULT in", values, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTNotIn(List<String> values) {
            addCriterion("REVIEW_RESULT not in", values, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTBetween(String value1, String value2) {
            addCriterion("REVIEW_RESULT between", value1, value2, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andREVIEW_RESULTNotBetween(String value1, String value2) {
            addCriterion("REVIEW_RESULT not between", value1, value2, "REVIEW_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIsNull() {
            addCriterion("BUSINESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIsNotNull() {
            addCriterion("BUSINESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEEqualTo(String value) {
            addCriterion("BUSINESS_TYPE =", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <>", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEGreaterThan(String value) {
            addCriterion("BUSINESS_TYPE >", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE >=", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELessThan(String value) {
            addCriterion("BUSINESS_TYPE <", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <=", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELike(String value) {
            addCriterion("BUSINESS_TYPE like", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotLike(String value) {
            addCriterion("BUSINESS_TYPE not like", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIn(List<String> values) {
            addCriterion("BUSINESS_TYPE in", values, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotIn(List<String> values) {
            addCriterion("BUSINESS_TYPE not in", values, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE between", value1, value2, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE not between", value1, value2, "BUSINESS_TYPE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 13 20:04:33 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}