package com.allscore.wireless.dao;

import com.allscore.wireless.dao.CheckBusiness;
import com.allscore.wireless.dao.CheckBusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int countByExample(CheckBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int deleteByExample(CheckBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int insert(CheckBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int insertSelective(CheckBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    List<CheckBusiness> selectByExample(CheckBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    CheckBusiness selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CheckBusiness record, @Param("example") CheckBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int updateByExample(@Param("record") CheckBusiness record, @Param("example") CheckBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int updateByPrimaryKeySelective(CheckBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_BUSSINESS
     *
     * @mbggenerated Sat Dec 12 12:03:52 CST 2015
     */
    int updateByPrimaryKey(CheckBusiness record);
}