package com.allscore.wireless.dao;

import com.allscore.wireless.dao.CheckError;
import com.allscore.wireless.dao.CheckErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int countByExample(CheckErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int deleteByExample(CheckErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int insert(CheckError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int insertSelective(CheckError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    List<CheckError> selectByExample(CheckErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    CheckError selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") CheckError record, @Param("example") CheckErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int updateByExample(@Param("record") CheckError record, @Param("example") CheckErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int updateByPrimaryKeySelective(CheckError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_CHECK_ERROR
     *
     * @mbggenerated Sun Dec 13 20:04:33 CST 2015
     */
    int updateByPrimaryKey(CheckError record);
}