package com.allscore.wireless.dao;

import com.allscore.wireless.dao.FundPool;
import com.allscore.wireless.dao.FundPoolExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="fundPoolMapper")
public interface FundPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int countByExample(FundPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int deleteByExample(FundPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int insert(FundPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int insertSelective(FundPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    List<FundPool> selectByExample(FundPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    FundPool selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") FundPool record, @Param("example") FundPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int updateByExample(@Param("record") FundPool record, @Param("example") FundPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int updateByPrimaryKeySelective(FundPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    int updateByPrimaryKey(FundPool record);
}