package com.allscore.wireless.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundPoolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public FundPoolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYIsNull() {
            addCriterion("CURR_MOENY is null");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYIsNotNull() {
            addCriterion("CURR_MOENY is not null");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYEqualTo(BigDecimal value) {
            addCriterion("CURR_MOENY =", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYNotEqualTo(BigDecimal value) {
            addCriterion("CURR_MOENY <>", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYGreaterThan(BigDecimal value) {
            addCriterion("CURR_MOENY >", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CURR_MOENY >=", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYLessThan(BigDecimal value) {
            addCriterion("CURR_MOENY <", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CURR_MOENY <=", value, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYIn(List<BigDecimal> values) {
            addCriterion("CURR_MOENY in", values, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYNotIn(List<BigDecimal> values) {
            addCriterion("CURR_MOENY not in", values, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURR_MOENY between", value1, value2, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andCURR_MOENYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURR_MOENY not between", value1, value2, "CURR_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYIsNull() {
            addCriterion("DAY_MOENY is null");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYIsNotNull() {
            addCriterion("DAY_MOENY is not null");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYEqualTo(BigDecimal value) {
            addCriterion("DAY_MOENY =", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYNotEqualTo(BigDecimal value) {
            addCriterion("DAY_MOENY <>", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYGreaterThan(BigDecimal value) {
            addCriterion("DAY_MOENY >", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_MOENY >=", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYLessThan(BigDecimal value) {
            addCriterion("DAY_MOENY <", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_MOENY <=", value, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYIn(List<BigDecimal> values) {
            addCriterion("DAY_MOENY in", values, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYNotIn(List<BigDecimal> values) {
            addCriterion("DAY_MOENY not in", values, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_MOENY between", value1, value2, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andDAY_MOENYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_MOENY not between", value1, value2, "DAY_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYIsNull() {
            addCriterion("FROZEN_MOENY is null");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYIsNotNull() {
            addCriterion("FROZEN_MOENY is not null");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYEqualTo(BigDecimal value) {
            addCriterion("FROZEN_MOENY =", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYNotEqualTo(BigDecimal value) {
            addCriterion("FROZEN_MOENY <>", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYGreaterThan(BigDecimal value) {
            addCriterion("FROZEN_MOENY >", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FROZEN_MOENY >=", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYLessThan(BigDecimal value) {
            addCriterion("FROZEN_MOENY <", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FROZEN_MOENY <=", value, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYIn(List<BigDecimal> values) {
            addCriterion("FROZEN_MOENY in", values, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYNotIn(List<BigDecimal> values) {
            addCriterion("FROZEN_MOENY not in", values, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROZEN_MOENY between", value1, value2, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andFROZEN_MOENYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROZEN_MOENY not between", value1, value2, "FROZEN_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYIsNull() {
            addCriterion("VALID_MOENY is null");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYIsNotNull() {
            addCriterion("VALID_MOENY is not null");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYEqualTo(BigDecimal value) {
            addCriterion("VALID_MOENY =", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYNotEqualTo(BigDecimal value) {
            addCriterion("VALID_MOENY <>", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYGreaterThan(BigDecimal value) {
            addCriterion("VALID_MOENY >", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VALID_MOENY >=", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYLessThan(BigDecimal value) {
            addCriterion("VALID_MOENY <", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VALID_MOENY <=", value, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYIn(List<BigDecimal> values) {
            addCriterion("VALID_MOENY in", values, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYNotIn(List<BigDecimal> values) {
            addCriterion("VALID_MOENY not in", values, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALID_MOENY between", value1, value2, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andVALID_MOENYNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALID_MOENY not between", value1, value2, "VALID_MOENY");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 02 20:14:29 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_FUND_POOL
     *
     * @mbggenerated Wed Dec 02 20:14:29 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}