package com.allscore.wireless.dao;

import com.allscore.wireless.dao.MemberPublic;
import com.allscore.wireless.dao.MemberPublicExample;
import com.allscore.wireless.dao.MemberPublicWithBLOBs;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="femberPublicMapper")
public interface MemberPublicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int countByExample(MemberPublicExample example);
    
    String randomMath();
    
    int checkRandomMath(String str);
    
    String maxMerchantCode();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int deleteByExample(MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int insert(MemberPublicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int insertSelective(MemberPublicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    List<MemberPublicWithBLOBs> selectByExampleWithBLOBs(MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    List<MemberPublic> selectByExample(MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    MemberPublicWithBLOBs selectByPrimaryKey(String ID);
    
    MemberPublicWithBLOBs selectByMerchantID(String merchantID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemberPublicWithBLOBs record, @Param("example") MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") MemberPublicWithBLOBs record, @Param("example") MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByExample(@Param("record") MemberPublic record, @Param("example") MemberPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByPrimaryKeySelective(MemberPublicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(MemberPublicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MEMBER_PUBLIC
     *
     * @mbggenerated Mon Dec 07 13:35:02 CST 2015
     */
    int updateByPrimaryKey(MemberPublic record);
}