package com.allscore.wireless.dao;

import com.allscore.wireless.dao.MerchantRate;
import com.allscore.wireless.dao.MerchantRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int countByExample(MerchantRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int deleteByExample(MerchantRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int insert(MerchantRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int insertSelective(MerchantRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    List<MerchantRate> selectByExample(MerchantRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    MerchantRate selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") MerchantRate record, @Param("example") MerchantRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int updateByExample(@Param("record") MerchantRate record, @Param("example") MerchantRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int updateByPrimaryKeySelective(MerchantRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MERCHANT_RATE
     *
     * @mbggenerated Thu Jan 21 10:36:32 CST 2016
     */
    int updateByPrimaryKey(MerchantRate record);
}