package com.allscore.wireless.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsgTemplateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public MsgTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIsNull() {
            addCriterion("PUBLIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIsNotNull() {
            addCriterion("PUBLIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDEqualTo(String value) {
            addCriterion("PUBLIC_ID =", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotEqualTo(String value) {
            addCriterion("PUBLIC_ID <>", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDGreaterThan(String value) {
            addCriterion("PUBLIC_ID >", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLIC_ID >=", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLessThan(String value) {
            addCriterion("PUBLIC_ID <", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLessThanOrEqualTo(String value) {
            addCriterion("PUBLIC_ID <=", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLike(String value) {
            addCriterion("PUBLIC_ID like", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotLike(String value) {
            addCriterion("PUBLIC_ID not like", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIn(List<String> values) {
            addCriterion("PUBLIC_ID in", values, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotIn(List<String> values) {
            addCriterion("PUBLIC_ID not in", values, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDBetween(String value1, String value2) {
            addCriterion("PUBLIC_ID between", value1, value2, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotBetween(String value1, String value2) {
            addCriterion("PUBLIC_ID not between", value1, value2, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDIsNull() {
            addCriterion("TEMPLATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDIsNotNull() {
            addCriterion("TEMPLATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDEqualTo(String value) {
            addCriterion("TEMPLATE_ID =", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDNotEqualTo(String value) {
            addCriterion("TEMPLATE_ID <>", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDGreaterThan(String value) {
            addCriterion("TEMPLATE_ID >", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_ID >=", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDLessThan(String value) {
            addCriterion("TEMPLATE_ID <", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDLessThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_ID <=", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDLike(String value) {
            addCriterion("TEMPLATE_ID like", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDNotLike(String value) {
            addCriterion("TEMPLATE_ID not like", value, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDIn(List<String> values) {
            addCriterion("TEMPLATE_ID in", values, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDNotIn(List<String> values) {
            addCriterion("TEMPLATE_ID not in", values, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDBetween(String value1, String value2) {
            addCriterion("TEMPLATE_ID between", value1, value2, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_IDNotBetween(String value1, String value2) {
            addCriterion("TEMPLATE_ID not between", value1, value2, "TEMPLATE_ID");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEIsNull() {
            addCriterion("TEMPLATE_TPYE is null");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEIsNotNull() {
            addCriterion("TEMPLATE_TPYE is not null");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEEqualTo(String value) {
            addCriterion("TEMPLATE_TPYE =", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYENotEqualTo(String value) {
            addCriterion("TEMPLATE_TPYE <>", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEGreaterThan(String value) {
            addCriterion("TEMPLATE_TPYE >", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_TPYE >=", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYELessThan(String value) {
            addCriterion("TEMPLATE_TPYE <", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYELessThanOrEqualTo(String value) {
            addCriterion("TEMPLATE_TPYE <=", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYELike(String value) {
            addCriterion("TEMPLATE_TPYE like", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYENotLike(String value) {
            addCriterion("TEMPLATE_TPYE not like", value, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEIn(List<String> values) {
            addCriterion("TEMPLATE_TPYE in", values, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYENotIn(List<String> values) {
            addCriterion("TEMPLATE_TPYE not in", values, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYEBetween(String value1, String value2) {
            addCriterion("TEMPLATE_TPYE between", value1, value2, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andTEMPLATE_TPYENotBetween(String value1, String value2) {
            addCriterion("TEMPLATE_TPYE not between", value1, value2, "TEMPLATE_TPYE");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andREMARKEqualTo(String value) {
            addCriterion("REMARK =", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThan(String value) {
            addCriterion("REMARK >", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThan(String value) {
            addCriterion("REMARK <", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLike(String value) {
            addCriterion("REMARK like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotLike(String value) {
            addCriterion("REMARK not like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKIn(List<String> values) {
            addCriterion("REMARK in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 13 13:39:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_MSG_TEMPLATE
     *
     * @mbggenerated Wed Jan 13 13:39:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}