package com.allscore.wireless.dao;

import com.allscore.wireless.dao.PosInfo;
import com.allscore.wireless.dao.PosInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository(value="posInfoMapper")
public interface PosInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int countByExample(PosInfoExample example);
    
    String selectMaxID();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int deleteByExample(PosInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int insert(PosInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int insertSelective(PosInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    List<PosInfo> selectByExample(PosInfoExample example);
    
    List<PosInfo> selectByExampleExport(PosInfoExample example);
    
    List<PosInfo> selectPosCkByExample(PosInfoExample example);
    
    List<PosInfo> selectCkByExampleExport(PosInfoExample example);//
    
    List<MemberPublic> selectMerchantName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    PosInfo selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") PosInfo record, @Param("example") PosInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int updateByExample(@Param("record") PosInfo record, @Param("example") PosInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int updateByPrimaryKeySelective(PosInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    int updateByPrimaryKey(PosInfo record);
}