package com.allscore.wireless.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PosInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public PosInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIsNull() {
            addCriterion("POS_SN is null");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIsNotNull() {
            addCriterion("POS_SN is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_SNEqualTo(String value) {
            addCriterion("POS_SN =", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotEqualTo(String value) {
            addCriterion("POS_SN <>", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNGreaterThan(String value) {
            addCriterion("POS_SN >", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNGreaterThanOrEqualTo(String value) {
            addCriterion("POS_SN >=", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLessThan(String value) {
            addCriterion("POS_SN <", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLessThanOrEqualTo(String value) {
            addCriterion("POS_SN <=", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLike(String value) {
            addCriterion("POS_SN like", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotLike(String value) {
            addCriterion("POS_SN not like", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIn(List<String> values) {
            addCriterion("POS_SN in", values, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotIn(List<String> values) {
            addCriterion("POS_SN not in", values, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNBetween(String value1, String value2) {
            addCriterion("POS_SN between", value1, value2, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotBetween(String value1, String value2) {
            addCriterion("POS_SN not between", value1, value2, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELIsNull() {
            addCriterion("POS_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELIsNotNull() {
            addCriterion("POS_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELEqualTo(String value) {
            addCriterion("POS_MODEL =", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELNotEqualTo(String value) {
            addCriterion("POS_MODEL <>", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELGreaterThan(String value) {
            addCriterion("POS_MODEL >", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELGreaterThanOrEqualTo(String value) {
            addCriterion("POS_MODEL >=", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELLessThan(String value) {
            addCriterion("POS_MODEL <", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELLessThanOrEqualTo(String value) {
            addCriterion("POS_MODEL <=", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELLike(String value) {
            addCriterion("POS_MODEL like", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELNotLike(String value) {
            addCriterion("POS_MODEL not like", value, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELIn(List<String> values) {
            addCriterion("POS_MODEL in", values, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELNotIn(List<String> values) {
            addCriterion("POS_MODEL not in", values, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELBetween(String value1, String value2) {
            addCriterion("POS_MODEL between", value1, value2, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andPOS_MODELNotBetween(String value1, String value2) {
            addCriterion("POS_MODEL not between", value1, value2, "POS_MODEL");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONIsNull() {
            addCriterion("COMMUNICATION is null");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONIsNotNull() {
            addCriterion("COMMUNICATION is not null");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONEqualTo(String value) {
            addCriterion("COMMUNICATION =", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONNotEqualTo(String value) {
            addCriterion("COMMUNICATION <>", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONGreaterThan(String value) {
            addCriterion("COMMUNICATION >", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONGreaterThanOrEqualTo(String value) {
            addCriterion("COMMUNICATION >=", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONLessThan(String value) {
            addCriterion("COMMUNICATION <", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONLessThanOrEqualTo(String value) {
            addCriterion("COMMUNICATION <=", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONLike(String value) {
            addCriterion("COMMUNICATION like", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONNotLike(String value) {
            addCriterion("COMMUNICATION not like", value, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONIn(List<String> values) {
            addCriterion("COMMUNICATION in", values, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONNotIn(List<String> values) {
            addCriterion("COMMUNICATION not in", values, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONBetween(String value1, String value2) {
            addCriterion("COMMUNICATION between", value1, value2, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andCOMMUNICATIONNotBetween(String value1, String value2) {
            addCriterion("COMMUNICATION not between", value1, value2, "COMMUNICATION");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andREMARKEqualTo(String value) {
            addCriterion("REMARK =", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThan(String value) {
            addCriterion("REMARK >", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThan(String value) {
            addCriterion("REMARK <", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLike(String value) {
            addCriterion("REMARK like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotLike(String value) {
            addCriterion("REMARK not like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKIn(List<String> values) {
            addCriterion("REMARK in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEIsNull() {
            addCriterion("FACTORY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEIsNotNull() {
            addCriterion("FACTORY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEEqualTo(String value) {
            addCriterion("FACTORY_NAME =", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMENotEqualTo(String value) {
            addCriterion("FACTORY_NAME <>", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEGreaterThan(String value) {
            addCriterion("FACTORY_NAME >", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FACTORY_NAME >=", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMELessThan(String value) {
            addCriterion("FACTORY_NAME <", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMELessThanOrEqualTo(String value) {
            addCriterion("FACTORY_NAME <=", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMELike(String value) {
            addCriterion("FACTORY_NAME like", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMENotLike(String value) {
            addCriterion("FACTORY_NAME not like", value, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEIn(List<String> values) {
            addCriterion("FACTORY_NAME in", values, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMENotIn(List<String> values) {
            addCriterion("FACTORY_NAME not in", values, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMEBetween(String value1, String value2) {
            addCriterion("FACTORY_NAME between", value1, value2, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andFACTORY_NAMENotBetween(String value1, String value2) {
            addCriterion("FACTORY_NAME not between", value1, value2, "FACTORY_NAME");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKIsNull() {
            addCriterion("POS_TLK is null");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKIsNotNull() {
            addCriterion("POS_TLK is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKEqualTo(String value) {
            addCriterion("POS_TLK =", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKNotEqualTo(String value) {
            addCriterion("POS_TLK <>", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKGreaterThan(String value) {
            addCriterion("POS_TLK >", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKGreaterThanOrEqualTo(String value) {
            addCriterion("POS_TLK >=", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKLessThan(String value) {
            addCriterion("POS_TLK <", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKLessThanOrEqualTo(String value) {
            addCriterion("POS_TLK <=", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKLike(String value) {
            addCriterion("POS_TLK like", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKNotLike(String value) {
            addCriterion("POS_TLK not like", value, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKIn(List<String> values) {
            addCriterion("POS_TLK in", values, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKNotIn(List<String> values) {
            addCriterion("POS_TLK not in", values, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKBetween(String value1, String value2) {
            addCriterion("POS_TLK between", value1, value2, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TLKNotBetween(String value1, String value2) {
            addCriterion("POS_TLK not between", value1, value2, "POS_TLK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKIsNull() {
            addCriterion("POS_TMK is null");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKIsNotNull() {
            addCriterion("POS_TMK is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKEqualTo(String value) {
            addCriterion("POS_TMK =", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKNotEqualTo(String value) {
            addCriterion("POS_TMK <>", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKGreaterThan(String value) {
            addCriterion("POS_TMK >", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKGreaterThanOrEqualTo(String value) {
            addCriterion("POS_TMK >=", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKLessThan(String value) {
            addCriterion("POS_TMK <", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKLessThanOrEqualTo(String value) {
            addCriterion("POS_TMK <=", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKLike(String value) {
            addCriterion("POS_TMK like", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKNotLike(String value) {
            addCriterion("POS_TMK not like", value, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKIn(List<String> values) {
            addCriterion("POS_TMK in", values, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKNotIn(List<String> values) {
            addCriterion("POS_TMK not in", values, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKBetween(String value1, String value2) {
            addCriterion("POS_TMK between", value1, value2, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_TMKNotBetween(String value1, String value2) {
            addCriterion("POS_TMK not between", value1, value2, "POS_TMK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKIsNull() {
            addCriterion("POS_PIK is null");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKIsNotNull() {
            addCriterion("POS_PIK is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKEqualTo(String value) {
            addCriterion("POS_PIK =", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKNotEqualTo(String value) {
            addCriterion("POS_PIK <>", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKGreaterThan(String value) {
            addCriterion("POS_PIK >", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKGreaterThanOrEqualTo(String value) {
            addCriterion("POS_PIK >=", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKLessThan(String value) {
            addCriterion("POS_PIK <", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKLessThanOrEqualTo(String value) {
            addCriterion("POS_PIK <=", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKLike(String value) {
            addCriterion("POS_PIK like", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKNotLike(String value) {
            addCriterion("POS_PIK not like", value, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKIn(List<String> values) {
            addCriterion("POS_PIK in", values, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKNotIn(List<String> values) {
            addCriterion("POS_PIK not in", values, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKBetween(String value1, String value2) {
            addCriterion("POS_PIK between", value1, value2, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_PIKNotBetween(String value1, String value2) {
            addCriterion("POS_PIK not between", value1, value2, "POS_PIK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKIsNull() {
            addCriterion("POS_MAK is null");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKIsNotNull() {
            addCriterion("POS_MAK is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKEqualTo(String value) {
            addCriterion("POS_MAK =", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKNotEqualTo(String value) {
            addCriterion("POS_MAK <>", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKGreaterThan(String value) {
            addCriterion("POS_MAK >", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKGreaterThanOrEqualTo(String value) {
            addCriterion("POS_MAK >=", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKLessThan(String value) {
            addCriterion("POS_MAK <", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKLessThanOrEqualTo(String value) {
            addCriterion("POS_MAK <=", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKLike(String value) {
            addCriterion("POS_MAK like", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKNotLike(String value) {
            addCriterion("POS_MAK not like", value, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKIn(List<String> values) {
            addCriterion("POS_MAK in", values, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKNotIn(List<String> values) {
            addCriterion("POS_MAK not in", values, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKBetween(String value1, String value2) {
            addCriterion("POS_MAK between", value1, value2, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_MAKNotBetween(String value1, String value2) {
            addCriterion("POS_MAK not between", value1, value2, "POS_MAK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKIsNull() {
            addCriterion("POS_TRK is null");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKIsNotNull() {
            addCriterion("POS_TRK is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKEqualTo(String value) {
            addCriterion("POS_TRK =", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKNotEqualTo(String value) {
            addCriterion("POS_TRK <>", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKGreaterThan(String value) {
            addCriterion("POS_TRK >", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKGreaterThanOrEqualTo(String value) {
            addCriterion("POS_TRK >=", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKLessThan(String value) {
            addCriterion("POS_TRK <", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKLessThanOrEqualTo(String value) {
            addCriterion("POS_TRK <=", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKLike(String value) {
            addCriterion("POS_TRK like", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKNotLike(String value) {
            addCriterion("POS_TRK not like", value, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKIn(List<String> values) {
            addCriterion("POS_TRK in", values, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKNotIn(List<String> values) {
            addCriterion("POS_TRK not in", values, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKBetween(String value1, String value2) {
            addCriterion("POS_TRK between", value1, value2, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andPOS_TRKNotBetween(String value1, String value2) {
            addCriterion("POS_TRK not between", value1, value2, "POS_TRK");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIsNull() {
            addCriterion("MERCHANT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIsNotNull() {
            addCriterion("MERCHANT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEEqualTo(String value) {
            addCriterion("MERCHANT_NAME =", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotEqualTo(String value) {
            addCriterion("MERCHANT_NAME <>", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEGreaterThan(String value) {
            addCriterion("MERCHANT_NAME >", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME >=", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELessThan(String value) {
            addCriterion("MERCHANT_NAME <", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME <=", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMELike(String value) {
            addCriterion("MERCHANT_NAME like", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotLike(String value) {
            addCriterion("MERCHANT_NAME not like", value, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEIn(List<String> values) {
            addCriterion("MERCHANT_NAME in", values, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotIn(List<String> values) {
            addCriterion("MERCHANT_NAME not in", values, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMEBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME between", value1, value2, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_NAMENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME not between", value1, value2, "MERCHANT_NAME");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONIsNull() {
            addCriterion("POS_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONIsNotNull() {
            addCriterion("POS_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONEqualTo(String value) {
            addCriterion("POS_LOCATION =", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONNotEqualTo(String value) {
            addCriterion("POS_LOCATION <>", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONGreaterThan(String value) {
            addCriterion("POS_LOCATION >", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONGreaterThanOrEqualTo(String value) {
            addCriterion("POS_LOCATION >=", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONLessThan(String value) {
            addCriterion("POS_LOCATION <", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONLessThanOrEqualTo(String value) {
            addCriterion("POS_LOCATION <=", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONLike(String value) {
            addCriterion("POS_LOCATION like", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONNotLike(String value) {
            addCriterion("POS_LOCATION not like", value, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONIn(List<String> values) {
            addCriterion("POS_LOCATION in", values, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONNotIn(List<String> values) {
            addCriterion("POS_LOCATION not in", values, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONBetween(String value1, String value2) {
            addCriterion("POS_LOCATION between", value1, value2, "POS_LOCATION");
            return (Criteria) this;
        }

        public Criteria andPOS_LOCATIONNotBetween(String value1, String value2) {
            addCriterion("POS_LOCATION not between", value1, value2, "POS_LOCATION");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 24 11:36:48 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_POS_INFO
     *
     * @mbggenerated Thu Dec 24 11:36:48 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}