package com.allscore.wireless.dao;

import com.allscore.wireless.dao.PromotionPlan;
import com.allscore.wireless.dao.PromotionPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int countByExample(PromotionPlanExample example);
    
    int countByExampleAdd(PromotionPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int deleteByExample(PromotionPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int insert(PromotionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int insertSelective(PromotionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    List<PromotionPlan> selectByExample(PromotionPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    PromotionPlan selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") PromotionPlan record, @Param("example") PromotionPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int updateByExample(@Param("record") PromotionPlan record, @Param("example") PromotionPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int updateByPrimaryKeySelective(PromotionPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_PROMOTION_PLAN
     *
     * @mbggenerated Thu Dec 10 15:29:34 CST 2015
     */
    int updateByPrimaryKey(PromotionPlan record);
}