package com.allscore.wireless.dao;

import com.allscore.wireless.dao.RoleManage;
import com.allscore.wireless.dao.RoleManageExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="roleManageMapper")
public interface RoleManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int countByExample(RoleManageExample example);
    
    String selectMaxRoleId();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int deleteByExample(RoleManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int insert(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int insertSelective(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    List<RoleManage> selectByExample(RoleManageExample example);
    
    List<RoleManage> selectRoleName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    RoleManage selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleManage record, @Param("example") RoleManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByExample(@Param("record") RoleManage record, @Param("example") RoleManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByPrimaryKeySelective(RoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByPrimaryKey(RoleManage record);
}