package com.allscore.wireless.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public RoleManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIsNull() {
            addCriterion("ROLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIsNotNull() {
            addCriterion("ROLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEEqualTo(String value) {
            addCriterion("ROLE_NAME =", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotEqualTo(String value) {
            addCriterion("ROLE_NAME <>", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEGreaterThan(String value) {
            addCriterion("ROLE_NAME >", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME >=", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELessThan(String value) {
            addCriterion("ROLE_NAME <", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELessThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME <=", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELike(String value) {
            addCriterion("ROLE_NAME like", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotLike(String value) {
            addCriterion("ROLE_NAME not like", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIn(List<String> values) {
            addCriterion("ROLE_NAME in", values, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotIn(List<String> values) {
            addCriterion("ROLE_NAME not in", values, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEBetween(String value1, String value2) {
            addCriterion("ROLE_NAME between", value1, value2, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotBetween(String value1, String value2) {
            addCriterion("ROLE_NAME not between", value1, value2, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIsNull() {
            addCriterion("ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andROLE_IDEqualTo(String value) {
            addCriterion("ROLE_ID =", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotEqualTo(String value) {
            addCriterion("ROLE_ID <>", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDGreaterThan(String value) {
            addCriterion("ROLE_ID >", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_ID >=", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLessThan(String value) {
            addCriterion("ROLE_ID <", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLessThanOrEqualTo(String value) {
            addCriterion("ROLE_ID <=", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLike(String value) {
            addCriterion("ROLE_ID like", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotLike(String value) {
            addCriterion("ROLE_ID not like", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIn(List<String> values) {
            addCriterion("ROLE_ID in", values, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotIn(List<String> values) {
            addCriterion("ROLE_ID not in", values, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDBetween(String value1, String value2) {
            addCriterion("ROLE_ID between", value1, value2, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotBetween(String value1, String value2) {
            addCriterion("ROLE_ID not between", value1, value2, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 15 09:00:09 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_ROLE_MANAGE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}