package com.allscore.wireless.dao;

import com.allscore.wireless.dao.ShopBusiness;
import com.allscore.wireless.dao.ShopBusinessExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository(value="shopBusinessMapper")
public interface ShopBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int countByExample(ShopBusinessExample example);
    
    int countTxBatchByExample(ShopBusinessExample example);
    
    String randomMathFour();
    
    String randomMathSix();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int deleteByExample(ShopBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int insert(ShopBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int insertSelective(ShopBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    List<ShopBusiness> selectByExample(ShopBusinessExample example);
    
    List<ShopBusiness> selectTxBatchByExample(ShopBusinessExample example);
    
    List<ShopBusiness> selectByBatchId(String batch_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    ShopBusiness selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") ShopBusiness record, @Param("example") ShopBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int updateByExample(@Param("record") ShopBusiness record, @Param("example") ShopBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int updateByPrimaryKeySelective(ShopBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_SHOP_BUSSINESS
     *
     * @mbggenerated Thu Dec 03 13:51:30 CST 2015
     */
    int updateByPrimaryKey(ShopBusiness record);
}