package com.allscore.wireless.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TokenInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public TokenInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIsNull() {
            addCriterion("PUBLIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIsNotNull() {
            addCriterion("PUBLIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDEqualTo(String value) {
            addCriterion("PUBLIC_ID =", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotEqualTo(String value) {
            addCriterion("PUBLIC_ID <>", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDGreaterThan(String value) {
            addCriterion("PUBLIC_ID >", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLIC_ID >=", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLessThan(String value) {
            addCriterion("PUBLIC_ID <", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLessThanOrEqualTo(String value) {
            addCriterion("PUBLIC_ID <=", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDLike(String value) {
            addCriterion("PUBLIC_ID like", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotLike(String value) {
            addCriterion("PUBLIC_ID not like", value, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDIn(List<String> values) {
            addCriterion("PUBLIC_ID in", values, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotIn(List<String> values) {
            addCriterion("PUBLIC_ID not in", values, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDBetween(String value1, String value2) {
            addCriterion("PUBLIC_ID between", value1, value2, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andPUBLIC_IDNotBetween(String value1, String value2) {
            addCriterion("PUBLIC_ID not between", value1, value2, "PUBLIC_ID");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENIsNull() {
            addCriterion("ACCESS_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENIsNotNull() {
            addCriterion("ACCESS_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENEqualTo(String value) {
            addCriterion("ACCESS_TOKEN =", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENNotEqualTo(String value) {
            addCriterion("ACCESS_TOKEN <>", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENGreaterThan(String value) {
            addCriterion("ACCESS_TOKEN >", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_TOKEN >=", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENLessThan(String value) {
            addCriterion("ACCESS_TOKEN <", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_TOKEN <=", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENLike(String value) {
            addCriterion("ACCESS_TOKEN like", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENNotLike(String value) {
            addCriterion("ACCESS_TOKEN not like", value, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENIn(List<String> values) {
            addCriterion("ACCESS_TOKEN in", values, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENNotIn(List<String> values) {
            addCriterion("ACCESS_TOKEN not in", values, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENBetween(String value1, String value2) {
            addCriterion("ACCESS_TOKEN between", value1, value2, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andACCESS_TOKENNotBetween(String value1, String value2) {
            addCriterion("ACCESS_TOKEN not between", value1, value2, "ACCESS_TOKEN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INIsNull() {
            addCriterion("EXPIRES_IN is null");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INIsNotNull() {
            addCriterion("EXPIRES_IN is not null");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INEqualTo(Short value) {
            addCriterion("EXPIRES_IN =", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INNotEqualTo(Short value) {
            addCriterion("EXPIRES_IN <>", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INGreaterThan(Short value) {
            addCriterion("EXPIRES_IN >", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INGreaterThanOrEqualTo(Short value) {
            addCriterion("EXPIRES_IN >=", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INLessThan(Short value) {
            addCriterion("EXPIRES_IN <", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INLessThanOrEqualTo(Short value) {
            addCriterion("EXPIRES_IN <=", value, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INIn(List<Short> values) {
            addCriterion("EXPIRES_IN in", values, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INNotIn(List<Short> values) {
            addCriterion("EXPIRES_IN not in", values, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INBetween(Short value1, Short value2) {
            addCriterion("EXPIRES_IN between", value1, value2, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andEXPIRES_INNotBetween(Short value1, Short value2) {
            addCriterion("EXPIRES_IN not between", value1, value2, "EXPIRES_IN");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andAPPIDIsNull() {
            addCriterion("APPID is null");
            return (Criteria) this;
        }

        public Criteria andAPPIDIsNotNull() {
            addCriterion("APPID is not null");
            return (Criteria) this;
        }

        public Criteria andAPPIDEqualTo(String value) {
            addCriterion("APPID =", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDNotEqualTo(String value) {
            addCriterion("APPID <>", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDGreaterThan(String value) {
            addCriterion("APPID >", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDGreaterThanOrEqualTo(String value) {
            addCriterion("APPID >=", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDLessThan(String value) {
            addCriterion("APPID <", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDLessThanOrEqualTo(String value) {
            addCriterion("APPID <=", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDLike(String value) {
            addCriterion("APPID like", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDNotLike(String value) {
            addCriterion("APPID not like", value, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDIn(List<String> values) {
            addCriterion("APPID in", values, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDNotIn(List<String> values) {
            addCriterion("APPID not in", values, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDBetween(String value1, String value2) {
            addCriterion("APPID between", value1, value2, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPIDNotBetween(String value1, String value2) {
            addCriterion("APPID not between", value1, value2, "APPID");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETIsNull() {
            addCriterion("APPSECRET is null");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETIsNotNull() {
            addCriterion("APPSECRET is not null");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETEqualTo(String value) {
            addCriterion("APPSECRET =", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETNotEqualTo(String value) {
            addCriterion("APPSECRET <>", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETGreaterThan(String value) {
            addCriterion("APPSECRET >", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETGreaterThanOrEqualTo(String value) {
            addCriterion("APPSECRET >=", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETLessThan(String value) {
            addCriterion("APPSECRET <", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETLessThanOrEqualTo(String value) {
            addCriterion("APPSECRET <=", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETLike(String value) {
            addCriterion("APPSECRET like", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETNotLike(String value) {
            addCriterion("APPSECRET not like", value, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETIn(List<String> values) {
            addCriterion("APPSECRET in", values, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETNotIn(List<String> values) {
            addCriterion("APPSECRET not in", values, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETBetween(String value1, String value2) {
            addCriterion("APPSECRET between", value1, value2, "APPSECRET");
            return (Criteria) this;
        }

        public Criteria andAPPSECRETNotBetween(String value1, String value2) {
            addCriterion("APPSECRET not between", value1, value2, "APPSECRET");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 27 16:30:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}