package com.allscore.wireless.dao;

import com.allscore.wireless.dao.TokenInfo;
import com.allscore.wireless.dao.TokenInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="tokenInfoMapper")
public interface TokenInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int countByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int deleteByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int insert(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int insertSelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    List<TokenInfo> selectByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    TokenInfo selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int updateByExample(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int updateByPrimaryKeySelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_TOKEN_INFO
     *
     * @mbggenerated Wed Jan 27 16:30:39 CST 2016
     */
    int updateByPrimaryKey(TokenInfo record);
}