package com.allscore.wireless.dao;

import com.allscore.wireless.dao.UserBase;
import com.allscore.wireless.dao.UserBaseExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository(value="userBaseMapper")
public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int countByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int deleteByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int insertSelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    
    List<UserBase> selectUserBaseByExample(UserBaseExample example);
    
    List<UserBase> selectByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    UserBase selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByExample(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByPrimaryKeySelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    int updateByPrimaryKey(UserBase record);
}