package com.allscore.wireless.dao;

import com.allscore.wireless.dao.UsersBussiness;

import com.allscore.wireless.dao.UsersBussinessExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository(value="usersBussinessMapper")
public interface UsersBussinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int countByExample(UsersBussinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int deleteByExample(UsersBussinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int insert(UsersBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int insertSelective(UsersBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    List<UsersBussiness> selectByExample(UsersBussinessExample example);
    
    List<UsersBussiness> selectBusinessByExampleType(UsersBussinessExample example);
    
    List<UsersBussiness> selectBusinessByExample(UsersBussinessExample example);
    
    List<UsersBussiness> selectXfBusinessByExample(UsersBussinessExample example);
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    UsersBussiness selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") UsersBussiness record, @Param("example") UsersBussinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByExample(@Param("record") UsersBussiness record, @Param("example") UsersBussinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByPrimaryKeySelective(UsersBussiness record);
    
    int updateByBusinessTime(UsersBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    int updateByPrimaryKey(UsersBussiness record);
}