package com.allscore.wireless.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsersBussinessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Integer limitEnd;
    
    protected String businessTime;
    
    protected String merchant_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public UsersBussinessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }
    
    public String getMerchant_code() {
		return merchant_code;
	}

	public void setMerchant_code(String merchantCode) {
		merchant_code = merchantCode;
	}

	public String getBusinessTime() {
		return businessTime;
	}

	public void setBusinessTime(String businessTime) {
		this.businessTime = businessTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUSER_IDEqualTo(String value) {
            addCriterion("USER_ID =", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThan(String value) {
            addCriterion("USER_ID >", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThan(String value) {
            addCriterion("USER_ID <", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDLike(String value) {
            addCriterion("USER_ID like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotLike(String value) {
            addCriterion("USER_ID not like", value, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDIn(List<String> values) {
            addCriterion("USER_ID in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andUSER_IDNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "USER_ID");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIsNull() {
            addCriterion("TRAN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIsNotNull() {
            addCriterion("TRAN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT =", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <>", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTGreaterThan(BigDecimal value) {
            addCriterion("TRAN_AMT >", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT >=", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTLessThan(BigDecimal value) {
            addCriterion("TRAN_AMT <", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <=", value, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT in", values, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT not in", values, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT between", value1, value2, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andTRAN_AMTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT not between", value1, value2, "TRAN_AMT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIsNull() {
            addCriterion("BUSINESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIsNotNull() {
            addCriterion("BUSINESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEEqualTo(String value) {
            addCriterion("BUSINESS_TYPE =", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <>", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEGreaterThan(String value) {
            addCriterion("BUSINESS_TYPE >", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE >=", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELessThan(String value) {
            addCriterion("BUSINESS_TYPE <", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <=", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPELike(String value) {
            addCriterion("BUSINESS_TYPE like", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotLike(String value) {
            addCriterion("BUSINESS_TYPE not like", value, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEIn(List<String> values) {
            addCriterion("BUSINESS_TYPE in", values, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotIn(List<String> values) {
            addCriterion("BUSINESS_TYPE not in", values, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPEBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE between", value1, value2, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TYPENotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE not between", value1, value2, "BUSINESS_TYPE");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIsNull() {
            addCriterion("ORDER_AMT is null");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIsNotNull() {
            addCriterion("ORDER_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT =", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT <>", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTGreaterThan(BigDecimal value) {
            addCriterion("ORDER_AMT >", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT >=", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTLessThan(BigDecimal value) {
            addCriterion("ORDER_AMT <", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMT <=", value, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMT in", values, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMT not in", values, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMT between", value1, value2, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andORDER_AMTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMT not between", value1, value2, "ORDER_AMT");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIsNull() {
            addCriterion("POUNDAGE is null");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIsNotNull() {
            addCriterion("POUNDAGE is not null");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE =", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE <>", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEGreaterThan(BigDecimal value) {
            addCriterion("POUNDAGE >", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE >=", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGELessThan(BigDecimal value) {
            addCriterion("POUNDAGE <", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGELessThanOrEqualTo(BigDecimal value) {
            addCriterion("POUNDAGE <=", value, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEIn(List<BigDecimal> values) {
            addCriterion("POUNDAGE in", values, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotIn(List<BigDecimal> values) {
            addCriterion("POUNDAGE not in", values, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POUNDAGE between", value1, value2, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andPOUNDAGENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POUNDAGE not between", value1, value2, "POUNDAGE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEIsNull() {
            addCriterion("BUSINESS_SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEIsNotNull() {
            addCriterion("BUSINESS_SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEEqualTo(String value) {
            addCriterion("BUSINESS_SOURCE =", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCENotEqualTo(String value) {
            addCriterion("BUSINESS_SOURCE <>", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEGreaterThan(String value) {
            addCriterion("BUSINESS_SOURCE >", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_SOURCE >=", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCELessThan(String value) {
            addCriterion("BUSINESS_SOURCE <", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCELessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_SOURCE <=", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCELike(String value) {
            addCriterion("BUSINESS_SOURCE like", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCENotLike(String value) {
            addCriterion("BUSINESS_SOURCE not like", value, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEIn(List<String> values) {
            addCriterion("BUSINESS_SOURCE in", values, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCENotIn(List<String> values) {
            addCriterion("BUSINESS_SOURCE not in", values, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCEBetween(String value1, String value2) {
            addCriterion("BUSINESS_SOURCE between", value1, value2, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_SOURCENotBetween(String value1, String value2) {
            addCriterion("BUSINESS_SOURCE not between", value1, value2, "BUSINESS_SOURCE");
            return (Criteria) this;
        }

        public Criteria andSERIALIsNull() {
            addCriterion("SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andSERIALIsNotNull() {
            addCriterion("SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andSERIALEqualTo(String value) {
            addCriterion("SERIAL =", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotEqualTo(String value) {
            addCriterion("SERIAL <>", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALGreaterThan(String value) {
            addCriterion("SERIAL >", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL >=", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLessThan(String value) {
            addCriterion("SERIAL <", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLessThanOrEqualTo(String value) {
            addCriterion("SERIAL <=", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALLike(String value) {
            addCriterion("SERIAL like", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotLike(String value) {
            addCriterion("SERIAL not like", value, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALIn(List<String> values) {
            addCriterion("SERIAL in", values, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotIn(List<String> values) {
            addCriterion("SERIAL not in", values, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALBetween(String value1, String value2) {
            addCriterion("SERIAL between", value1, value2, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andSERIALNotBetween(String value1, String value2) {
            addCriterion("SERIAL not between", value1, value2, "SERIAL");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTIsNull() {
            addCriterion("BUSINESS_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTIsNotNull() {
            addCriterion("BUSINESS_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTEqualTo(String value) {
            addCriterion("BUSINESS_RESULT =", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTNotEqualTo(String value) {
            addCriterion("BUSINESS_RESULT <>", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTGreaterThan(String value) {
            addCriterion("BUSINESS_RESULT >", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_RESULT >=", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTLessThan(String value) {
            addCriterion("BUSINESS_RESULT <", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_RESULT <=", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTLike(String value) {
            addCriterion("BUSINESS_RESULT like", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTNotLike(String value) {
            addCriterion("BUSINESS_RESULT not like", value, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTIn(List<String> values) {
            addCriterion("BUSINESS_RESULT in", values, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTNotIn(List<String> values) {
            addCriterion("BUSINESS_RESULT not in", values, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTBetween(String value1, String value2) {
            addCriterion("BUSINESS_RESULT between", value1, value2, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_RESULTNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_RESULT not between", value1, value2, "BUSINESS_RESULT");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIsNull() {
            addCriterion("POS_SN is null");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIsNotNull() {
            addCriterion("POS_SN is not null");
            return (Criteria) this;
        }

        public Criteria andPOS_SNEqualTo(String value) {
            addCriterion("POS_SN =", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotEqualTo(String value) {
            addCriterion("POS_SN <>", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNGreaterThan(String value) {
            addCriterion("POS_SN >", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNGreaterThanOrEqualTo(String value) {
            addCriterion("POS_SN >=", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLessThan(String value) {
            addCriterion("POS_SN <", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLessThanOrEqualTo(String value) {
            addCriterion("POS_SN <=", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNLike(String value) {
            addCriterion("POS_SN like", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotLike(String value) {
            addCriterion("POS_SN not like", value, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNIn(List<String> values) {
            addCriterion("POS_SN in", values, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotIn(List<String> values) {
            addCriterion("POS_SN not in", values, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNBetween(String value1, String value2) {
            addCriterion("POS_SN between", value1, value2, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andPOS_SNNotBetween(String value1, String value2) {
            addCriterion("POS_SN not between", value1, value2, "POS_SN");
            return (Criteria) this;
        }

        public Criteria andINTEGRALIsNull() {
            addCriterion("INTEGRAL is null");
            return (Criteria) this;
        }

        public Criteria andINTEGRALIsNotNull() {
            addCriterion("INTEGRAL is not null");
            return (Criteria) this;
        }

        public Criteria andINTEGRALEqualTo(Long value) {
            addCriterion("INTEGRAL =", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALNotEqualTo(Long value) {
            addCriterion("INTEGRAL <>", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALGreaterThan(Long value) {
            addCriterion("INTEGRAL >", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALGreaterThanOrEqualTo(Long value) {
            addCriterion("INTEGRAL >=", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALLessThan(Long value) {
            addCriterion("INTEGRAL <", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALLessThanOrEqualTo(Long value) {
            addCriterion("INTEGRAL <=", value, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALIn(List<Long> values) {
            addCriterion("INTEGRAL in", values, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALNotIn(List<Long> values) {
            addCriterion("INTEGRAL not in", values, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALBetween(Long value1, Long value2) {
            addCriterion("INTEGRAL between", value1, value2, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andINTEGRALNotBetween(Long value1, Long value2) {
            addCriterion("INTEGRAL not between", value1, value2, "INTEGRAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALIsNull() {
            addCriterion("SOURCE_SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALIsNotNull() {
            addCriterion("SOURCE_SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALEqualTo(String value) {
            addCriterion("SOURCE_SERIAL =", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALNotEqualTo(String value) {
            addCriterion("SOURCE_SERIAL <>", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALGreaterThan(String value) {
            addCriterion("SOURCE_SERIAL >", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_SERIAL >=", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALLessThan(String value) {
            addCriterion("SOURCE_SERIAL <", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_SERIAL <=", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALLike(String value) {
            addCriterion("SOURCE_SERIAL like", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALNotLike(String value) {
            addCriterion("SOURCE_SERIAL not like", value, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALIn(List<String> values) {
            addCriterion("SOURCE_SERIAL in", values, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALNotIn(List<String> values) {
            addCriterion("SOURCE_SERIAL not in", values, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALBetween(String value1, String value2) {
            addCriterion("SOURCE_SERIAL between", value1, value2, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSOURCE_SERIALNotBetween(String value1, String value2) {
            addCriterion("SOURCE_SERIAL not between", value1, value2, "SOURCE_SERIAL");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIsNull() {
            addCriterion("CARD_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBEREqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERLike(String value) {
            addCriterion("CARD_NUMBER like", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERIn(List<String> values) {
            addCriterion("CARD_NUMBER in", values, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotIn(List<String> values) {
            addCriterion("CARD_NUMBER not in", values, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andCARD_NUMBERNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2, "CARD_NUMBER");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMENotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMELessThan(String value) {
            addCriterion("BANK_NAME <", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMELessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMELike(String value) {
            addCriterion("BANK_NAME like", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMENotLike(String value) {
            addCriterion("BANK_NAME not like", value, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMENotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMEBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andBANK_NAMENotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "BANK_NAME");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREIsNull() {
            addCriterion("SERVICE_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREIsNotNull() {
            addCriterion("SERVICE_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREEqualTo(Short value) {
            addCriterion("SERVICE_SCORE =", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCORENotEqualTo(Short value) {
            addCriterion("SERVICE_SCORE <>", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREGreaterThan(Short value) {
            addCriterion("SERVICE_SCORE >", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREGreaterThanOrEqualTo(Short value) {
            addCriterion("SERVICE_SCORE >=", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCORELessThan(Short value) {
            addCriterion("SERVICE_SCORE <", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCORELessThanOrEqualTo(Short value) {
            addCriterion("SERVICE_SCORE <=", value, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREIn(List<Short> values) {
            addCriterion("SERVICE_SCORE in", values, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCORENotIn(List<Short> values) {
            addCriterion("SERVICE_SCORE not in", values, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCOREBetween(Short value1, Short value2) {
            addCriterion("SERVICE_SCORE between", value1, value2, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andSERVICE_SCORENotBetween(Short value1, Short value2) {
            addCriterion("SERVICE_SCORE not between", value1, value2, "SERVICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREIsNull() {
            addCriterion("ENVIRONMENT_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREIsNotNull() {
            addCriterion("ENVIRONMENT_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREEqualTo(Short value) {
            addCriterion("ENVIRONMENT_SCORE =", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCORENotEqualTo(Short value) {
            addCriterion("ENVIRONMENT_SCORE <>", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREGreaterThan(Short value) {
            addCriterion("ENVIRONMENT_SCORE >", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREGreaterThanOrEqualTo(Short value) {
            addCriterion("ENVIRONMENT_SCORE >=", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCORELessThan(Short value) {
            addCriterion("ENVIRONMENT_SCORE <", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCORELessThanOrEqualTo(Short value) {
            addCriterion("ENVIRONMENT_SCORE <=", value, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREIn(List<Short> values) {
            addCriterion("ENVIRONMENT_SCORE in", values, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCORENotIn(List<Short> values) {
            addCriterion("ENVIRONMENT_SCORE not in", values, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCOREBetween(Short value1, Short value2) {
            addCriterion("ENVIRONMENT_SCORE between", value1, value2, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andENVIRONMENT_SCORENotBetween(Short value1, Short value2) {
            addCriterion("ENVIRONMENT_SCORE not between", value1, value2, "ENVIRONMENT_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREIsNull() {
            addCriterion("PRICE_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREIsNotNull() {
            addCriterion("PRICE_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREEqualTo(Short value) {
            addCriterion("PRICE_SCORE =", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCORENotEqualTo(Short value) {
            addCriterion("PRICE_SCORE <>", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREGreaterThan(Short value) {
            addCriterion("PRICE_SCORE >", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREGreaterThanOrEqualTo(Short value) {
            addCriterion("PRICE_SCORE >=", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCORELessThan(Short value) {
            addCriterion("PRICE_SCORE <", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCORELessThanOrEqualTo(Short value) {
            addCriterion("PRICE_SCORE <=", value, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREIn(List<Short> values) {
            addCriterion("PRICE_SCORE in", values, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCORENotIn(List<Short> values) {
            addCriterion("PRICE_SCORE not in", values, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCOREBetween(Short value1, Short value2) {
            addCriterion("PRICE_SCORE between", value1, value2, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andPRICE_SCORENotBetween(Short value1, Short value2) {
            addCriterion("PRICE_SCORE not between", value1, value2, "PRICE_SCORE");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIsNull() {
            addCriterion("BUSINESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIsNotNull() {
            addCriterion("BUSINESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEEqualTo(Date value) {
            addCriterion("BUSINESS_TIME =", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotEqualTo(Date value) {
            addCriterion("BUSINESS_TIME <>", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEGreaterThan(Date value) {
            addCriterion("BUSINESS_TIME >", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("BUSINESS_TIME >=", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMELessThan(Date value) {
            addCriterion("BUSINESS_TIME <", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMELessThanOrEqualTo(Date value) {
            addCriterion("BUSINESS_TIME <=", value, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEIn(List<Date> values) {
            addCriterion("BUSINESS_TIME in", values, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotIn(List<Date> values) {
            addCriterion("BUSINESS_TIME not in", values, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMEBetween(Date value1, Date value2) {
            addCriterion("BUSINESS_TIME between", value1, value2, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andBUSINESS_TIMENotBetween(Date value1, Date value2) {
            addCriterion("BUSINESS_TIME not between", value1, value2, "BUSINESS_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 27 15:12:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USERS_BUSSINESS
     *
     * @mbggenerated Fri Nov 27 15:12:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}