package com.allscore.wireless.dao;

import com.allscore.wireless.dao.Users;
import com.allscore.wireless.dao.UsersExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository(value="usersMapper")
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    List<Users> selectByExample(UsersExample example);
    
    List<Users> selectByMember_card(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    Users selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USERS
     *
     * @mbggenerated Mon Nov 30 13:04:40 CST 2015
     */
    int updateByPrimaryKey(Users record);
    
    Users selectByCondition(Users record);
}