package com.allscore.wireless.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserBaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Integer limitEnd;
    
    protected String loginName;
    
    protected String loginPwd;
    
    protected String status;

    public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	
	public String getLoginPwd() {
		return loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}
    
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public UserBaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEIsNull() {
            addCriterion("LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEIsNotNull() {
            addCriterion("LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEEqualTo(String value) {
            addCriterion("LOGIN_NAME =", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMENotEqualTo(String value) {
            addCriterion("LOGIN_NAME <>", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEGreaterThan(String value) {
            addCriterion("LOGIN_NAME >", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME >=", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMELessThan(String value) {
            addCriterion("LOGIN_NAME <", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMELessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME <=", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMELike(String value) {
            addCriterion("LOGIN_NAME like", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMENotLike(String value) {
            addCriterion("LOGIN_NAME not like", value, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEIn(List<String> values) {
            addCriterion("LOGIN_NAME in", values, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMENotIn(List<String> values) {
            addCriterion("LOGIN_NAME not in", values, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMEBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME between", value1, value2, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_NAMENotBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME not between", value1, value2, "LOGIN_NAME");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDIsNull() {
            addCriterion("LOGIN_PWD is null");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDIsNotNull() {
            addCriterion("LOGIN_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDEqualTo(String value) {
            addCriterion("LOGIN_PWD =", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDNotEqualTo(String value) {
            addCriterion("LOGIN_PWD <>", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDGreaterThan(String value) {
            addCriterion("LOGIN_PWD >", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD >=", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDLessThan(String value) {
            addCriterion("LOGIN_PWD <", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD <=", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDLike(String value) {
            addCriterion("LOGIN_PWD like", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDNotLike(String value) {
            addCriterion("LOGIN_PWD not like", value, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDIn(List<String> values) {
            addCriterion("LOGIN_PWD in", values, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDNotIn(List<String> values) {
            addCriterion("LOGIN_PWD not in", values, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD between", value1, value2, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andLOGIN_PWDNotBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD not between", value1, value2, "LOGIN_PWD");
            return (Criteria) this;
        }

        public Criteria andBALANCEIsNull() {
            addCriterion("BALANCE is null");
            return (Criteria) this;
        }

        public Criteria andBALANCEIsNotNull() {
            addCriterion("BALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andBALANCEEqualTo(BigDecimal value) {
            addCriterion("BALANCE =", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotEqualTo(BigDecimal value) {
            addCriterion("BALANCE <>", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEGreaterThan(BigDecimal value) {
            addCriterion("BALANCE >", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE >=", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCELessThan(BigDecimal value) {
            addCriterion("BALANCE <", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCELessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE <=", value, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEIn(List<BigDecimal> values) {
            addCriterion("BALANCE in", values, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotIn(List<BigDecimal> values) {
            addCriterion("BALANCE not in", values, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE between", value1, value2, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andBALANCENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE not between", value1, value2, "BALANCE");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andUPDATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "UPDATE_TIME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIsNull() {
            addCriterion("ROLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIsNotNull() {
            addCriterion("ROLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEEqualTo(String value) {
            addCriterion("ROLE_NAME =", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotEqualTo(String value) {
            addCriterion("ROLE_NAME <>", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEGreaterThan(String value) {
            addCriterion("ROLE_NAME >", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME >=", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELessThan(String value) {
            addCriterion("ROLE_NAME <", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELessThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME <=", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMELike(String value) {
            addCriterion("ROLE_NAME like", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotLike(String value) {
            addCriterion("ROLE_NAME not like", value, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEIn(List<String> values) {
            addCriterion("ROLE_NAME in", values, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotIn(List<String> values) {
            addCriterion("ROLE_NAME not in", values, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMEBetween(String value1, String value2) {
            addCriterion("ROLE_NAME between", value1, value2, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_NAMENotBetween(String value1, String value2) {
            addCriterion("ROLE_NAME not between", value1, value2, "ROLE_NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_DECIsNull() {
            addCriterion("ROLE_DEC is null");
            return (Criteria) this;
        }

        public Criteria andROLE_DECIsNotNull() {
            addCriterion("ROLE_DEC is not null");
            return (Criteria) this;
        }

        public Criteria andROLE_DECEqualTo(String value) {
            addCriterion("ROLE_DEC =", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECNotEqualTo(String value) {
            addCriterion("ROLE_DEC <>", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECGreaterThan(String value) {
            addCriterion("ROLE_DEC >", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_DEC >=", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECLessThan(String value) {
            addCriterion("ROLE_DEC <", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECLessThanOrEqualTo(String value) {
            addCriterion("ROLE_DEC <=", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECLike(String value) {
            addCriterion("ROLE_DEC like", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECNotLike(String value) {
            addCriterion("ROLE_DEC not like", value, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECIn(List<String> values) {
            addCriterion("ROLE_DEC in", values, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECNotIn(List<String> values) {
            addCriterion("ROLE_DEC not in", values, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECBetween(String value1, String value2) {
            addCriterion("ROLE_DEC between", value1, value2, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andROLE_DECNotBetween(String value1, String value2) {
            addCriterion("ROLE_DEC not between", value1, value2, "ROLE_DEC");
            return (Criteria) this;
        }

        public Criteria andMOBILEIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMOBILEIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMOBILEEqualTo(String value) {
            addCriterion("MOBILE =", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEGreaterThan(String value) {
            addCriterion("MOBILE >", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELessThan(String value) {
            addCriterion("MOBILE <", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELike(String value) {
            addCriterion("MOBILE like", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotLike(String value) {
            addCriterion("MOBILE not like", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEIn(List<String> values) {
            addCriterion("MOBILE in", values, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEMAILEqualTo(String value) {
            addCriterion("EMAIL =", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThan(String value) {
            addCriterion("EMAIL >", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThan(String value) {
            addCriterion("EMAIL <", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLike(String value) {
            addCriterion("EMAIL like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotLike(String value) {
            addCriterion("EMAIL not like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILIn(List<String> values) {
            addCriterion("EMAIL in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNAMEEqualTo(String value) {
            addCriterion("NAME =", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotEqualTo(String value) {
            addCriterion("NAME <>", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThan(String value) {
            addCriterion("NAME >", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThan(String value) {
            addCriterion("NAME <", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELike(String value) {
            addCriterion("NAME like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotLike(String value) {
            addCriterion("NAME not like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEIn(List<String> values) {
            addCriterion("NAME in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotIn(List<String> values) {
            addCriterion("NAME not in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIsNull() {
            addCriterion("ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andROLE_IDEqualTo(String value) {
            addCriterion("ROLE_ID =", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotEqualTo(String value) {
            addCriterion("ROLE_ID <>", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDGreaterThan(String value) {
            addCriterion("ROLE_ID >", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_ID >=", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLessThan(String value) {
            addCriterion("ROLE_ID <", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLessThanOrEqualTo(String value) {
            addCriterion("ROLE_ID <=", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDLike(String value) {
            addCriterion("ROLE_ID like", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotLike(String value) {
            addCriterion("ROLE_ID not like", value, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDIn(List<String> values) {
            addCriterion("ROLE_ID in", values, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotIn(List<String> values) {
            addCriterion("ROLE_ID not in", values, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDBetween(String value1, String value2) {
            addCriterion("ROLE_ID between", value1, value2, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andROLE_IDNotBetween(String value1, String value2) {
            addCriterion("ROLE_ID not between", value1, value2, "ROLE_ID");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNull() {
            addCriterion("MERCHANT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIsNotNull() {
            addCriterion("MERCHANT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEEqualTo(String value) {
            addCriterion("MERCHANT_CODE =", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotEqualTo(String value) {
            addCriterion("MERCHANT_CODE <>", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThan(String value) {
            addCriterion("MERCHANT_CODE >", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE >=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThan(String value) {
            addCriterion("MERCHANT_CODE <", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_CODE <=", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODELike(String value) {
            addCriterion("MERCHANT_CODE like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotLike(String value) {
            addCriterion("MERCHANT_CODE not like", value, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEIn(List<String> values) {
            addCriterion("MERCHANT_CODE in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotIn(List<String> values) {
            addCriterion("MERCHANT_CODE not in", values, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODEBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andMERCHANT_CODENotBetween(String value1, String value2) {
            addCriterion("MERCHANT_CODE not between", value1, value2, "MERCHANT_CODE");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDIsNull() {
            addCriterion("SESSIONID is null");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDIsNotNull() {
            addCriterion("SESSIONID is not null");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDEqualTo(String value) {
            addCriterion("SESSIONID =", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDNotEqualTo(String value) {
            addCriterion("SESSIONID <>", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDGreaterThan(String value) {
            addCriterion("SESSIONID >", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDGreaterThanOrEqualTo(String value) {
            addCriterion("SESSIONID >=", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDLessThan(String value) {
            addCriterion("SESSIONID <", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDLessThanOrEqualTo(String value) {
            addCriterion("SESSIONID <=", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDLike(String value) {
            addCriterion("SESSIONID like", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDNotLike(String value) {
            addCriterion("SESSIONID not like", value, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDIn(List<String> values) {
            addCriterion("SESSIONID in", values, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDNotIn(List<String> values) {
            addCriterion("SESSIONID not in", values, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDBetween(String value1, String value2) {
            addCriterion("SESSIONID between", value1, value2, "SESSIONID");
            return (Criteria) this;
        }

        public Criteria andSESSIONIDNotBetween(String value1, String value2) {
            addCriterion("SESSIONID not between", value1, value2, "SESSIONID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 15 09:00:09 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WX_USER_BASE
     *
     * @mbggenerated Tue Dec 15 09:00:09 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}